version: "3.7"
services:
  rabbitmq:
    container_name: "rabbit-mq"
    image: rabbitmq:3-management
    hostname: "rabbit1"
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
       NAME: "some-rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"